// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ER-btP-StEPYPMzCMRCtyCGJrAvIR8g',
    appId: '1:160374676664:web:d4fbe044e431f4fc4a284d',
    messagingSenderId: '160374676664',
    projectId: 'gustosa-66729',
    authDomain: 'gustosa-66729.firebaseapp.com',
    storageBucket: 'gustosa-66729.appspot.com',
    measurementId: 'G-VMNBCXLEHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsVQk3Cf9HVfF9v3o_oeqoVr4VWn0-gpY',
    appId: '1:160374676664:android:dd5ddf662fd8e8af4a284d',
    messagingSenderId: '160374676664',
    projectId: 'gustosa-66729',
    storageBucket: 'gustosa-66729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxulAfM72plhtal1aBG8hTsz6o58rkhRI',
    appId: '1:160374676664:ios:96c8648d121811694a284d',
    messagingSenderId: '160374676664',
    projectId: 'gustosa-66729',
    storageBucket: 'gustosa-66729.appspot.com',
    androidClientId: '160374676664-2rvcn68lopm7n4ui7p67npqtc0s0jn89.apps.googleusercontent.com',
    iosClientId: '160374676664-slvhdrm8rrkpf4cifdi1d841jfghbeil.apps.googleusercontent.com',
    iosBundleId: 'com.example.gustosa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxulAfM72plhtal1aBG8hTsz6o58rkhRI',
    appId: '1:160374676664:ios:96c8648d121811694a284d',
    messagingSenderId: '160374676664',
    projectId: 'gustosa-66729',
    storageBucket: 'gustosa-66729.appspot.com',
    androidClientId: '160374676664-2rvcn68lopm7n4ui7p67npqtc0s0jn89.apps.googleusercontent.com',
    iosClientId: '160374676664-slvhdrm8rrkpf4cifdi1d841jfghbeil.apps.googleusercontent.com',
    iosBundleId: 'com.example.gustosa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ER-btP-StEPYPMzCMRCtyCGJrAvIR8g',
    appId: '1:160374676664:web:1a3efa8e2334e6e44a284d',
    messagingSenderId: '160374676664',
    projectId: 'gustosa-66729',
    authDomain: 'gustosa-66729.firebaseapp.com',
    storageBucket: 'gustosa-66729.appspot.com',
    measurementId: 'G-SQ25JNWHZF',
  );

}